"""
POD-Bench v2 — Canonical Extreme Scenario Catalog (60 scenarios, 8 archetypes)

Design: "Archetype x Specificity Gradient" (PCogAlignBench, SocialIQA, RVBench)
Each scenario defines unambiguous TPO constraints with cross-cultural consensus.

Instance generation:
  scenario x constrained_axis x compatible_user -> one benchmark instance
"""

# ═══════════════════════════════════════════════════════════
#  Helper to build scenario dicts compactly
# ═══════════════════════════════════════════════════════════

def _sc(sid, arch, name, tpo,
        gc_compat, gc_incompat,
        co_compat=None, co_incompat=None,
        pa_compat=None, pa_incompat=None,
        q_explicit=None, q_implicit=None,
        justification=""):
    sc = {
        "scenario_id": sid, "archetype": arch, "name": name, "tpo": tpo,
        "garment_category": {"compatible": gc_compat,
                             "incompatible": gc_incompat},
        "justification": justification,
    }
    if co_compat or co_incompat:
        sc["color"] = {"compatible": co_compat, "incompatible": co_incompat}
    else:
        sc["color"] = None
    if pa_compat or pa_incompat:
        sc["pattern"] = {"compatible": pa_compat, "incompatible": pa_incompat}
    else:
        sc["pattern"] = None
    sc["query_seeds"] = {"explicit": q_explicit or [], "implicit": q_implicit or []}
    return sc


# ═══════════════════════════════════════════════════════════
#  ARCHETYPE REGISTRY
# ═══════════════════════════════════════════════════════════

SCENARIO_ARCHETYPES = {
    "extreme_cold":      "Extreme Cold / Winter",
    "extreme_heat":      "Extreme Heat / Summer",
    "ultra_formal":      "Ultra-Formal / Ceremonial",
    "mourning_somber":   "Mourning / Somber / Sacred",
    "athletic_physical": "Athletic / Physical Activity",
    "weather_extreme":   "Severe Weather Events",
    "semi_formal_social":"Semi-Formal Social",
    "casual_outdoor":    "Casual Outdoor / Leisure",
}

# ═══════════════════════════════════════════════════════════
#  CANONICAL SCENARIOS (60 total)
# ═══════════════════════════════════════════════════════════

CANONICAL_SCENARIOS = [

    # ── ARCHETYPE 1: EXTREME COLD (8) ─────────────────────
    _sc("cold_blizzard_outdoor", "extreme_cold",
        "Blizzard & Sub-zero Outdoor All-day",
        {"time": {"season": "winter", "weather": "snowy"},
         "place": {"indoor_outdoor": "outdoor"},
         "occasion": {"formality_required": "casual"}},
        gc_compat=["parka", "coat", "trench_coat"],
        gc_incompat=["shorts", "tank_top", "t_shirt", "dress", "skirt"],
        q_explicit=["It's going to be a blizzard with sub-zero temperatures and I'll be outside all day. What should I wear?",
                     "Heavy snow and freezing winds are forecast — I need an outfit for spending the whole day outdoors."],
        q_implicit=["I'm heading to a winter festival in the mountains this weekend. Outfit advice?",
                     "Going to an outdoor holiday market during the snowstorm — what should I wear?"],
        justification="Sub-zero blizzard makes light clothing a hypothermia risk."),

    _sc("cold_winter_wedding_outdoor", "extreme_cold",
        "Outdoor Winter Wedding (Guest)",
        {"time": {"season": "winter", "weather": "cold"},
         "place": {"venue": "wedding_venue", "indoor_outdoor": "outdoor"},
         "occasion": {"activity": "ceremony_attendance", "formality_required": "formal"}},
        gc_compat=["coat", "trench_coat", "blazer"],
        gc_incompat=["shorts", "tank_top", "t_shirt", "hoodie"],
        co_compat=["black", "navy", "gray", "beige", "blue", "purple"],
        co_incompat=["orange", "yellow"],
        pa_compat=["solid", "striped"],
        pa_incompat=["camouflage", "graphic_print", "animal_print"],
        q_explicit=["Attending an outdoor winter wedding ceremony — it's below freezing. What should I wear?"],
        q_implicit=["My friend's getting married at an outdoor venue in January. Outfit advice?"],
        justification="Outdoor winter ceremony requires warmth + formality."),

    _sc("cold_dawn_commute", "extreme_cold",
        "Freezing Winter Dawn Commute",
        {"time": {"season": "winter", "weather": "cold", "time_of_day": "morning"},
         "place": {"indoor_outdoor": "outdoor"},
         "occasion": {"activity": "travel"}},
        gc_compat=["coat", "parka", "trench_coat", "jacket"],
        gc_incompat=["shorts", "tank_top", "t_shirt"],
        q_explicit=["It's freezing at dawn and I have a long walk to the station. What should I wear?"],
        q_implicit=["I need to commute across town early on a bitter winter morning. Outfit?"],
        justification="Walking in freezing dawn temperatures in shorts/tank top is impractical."),

    _sc("cold_ski_resort_town", "extreme_cold",
        "Ski Resort Town Sightseeing",
        {"time": {"season": "winter", "weather": "snowy"},
         "place": {"indoor_outdoor": "mixed"},
         "occasion": {"activity": "travel", "formality_required": "casual"}},
        gc_compat=["parka", "coat", "jacket", "sweater", "windbreaker"],
        gc_incompat=["shorts", "tank_top", "dress", "skirt"],
        q_explicit=["I'm walking around a snowy ski resort town all day. What should I wear?"],
        q_implicit=["Heading to a mountain resort village for a weekend trip. Outfit advice?"],
        justification="Snowy mountain town makes exposed-skin clothing impractical."),

    _sc("cold_military_memorial", "extreme_cold",
        "Outdoor Winter Military Memorial Ceremony",
        {"time": {"season": "winter", "weather": "cold"},
         "place": {"indoor_outdoor": "outdoor"},
         "occasion": {"activity": "ceremony_attendance", "formality_required": "formal"}},
        gc_compat=["coat", "trench_coat", "blazer"],
        gc_incompat=["shorts", "tank_top", "hoodie", "t_shirt"],
        co_compat=["black", "navy", "gray"],
        co_incompat=["orange", "yellow", "pink", "red"],
        pa_compat=["solid"],
        pa_incompat=["graphic_print", "camouflage", "animal_print", "floral"],
        q_explicit=["Attending an outdoor military memorial in winter. What should I wear?"],
        q_implicit=["Going to a veteran's memorial ceremony this January. Outfit?"],
        justification="Military memorials demand dark formal attire; casual/bright is disrespectful + freezing."),

    _sc("cold_outdoor_camping", "extreme_cold",
        "Winter Wilderness Camping",
        {"time": {"season": "winter", "weather": "cold"},
         "place": {"indoor_outdoor": "outdoor"},
         "occasion": {"activity": "travel", "formality_required": "very_casual"}},
        gc_compat=["parka", "coat", "sweater", "jacket"],
        gc_incompat=["shorts", "tank_top", "t_shirt", "dress", "blazer"],
        q_explicit=["I'm going winter camping in sub-zero weather. What should I wear?"],
        q_implicit=["Heading out for a wilderness camping trip in January. Outfit advice?"],
        justification="Winter camping with minimal clothing is a survival hazard."),

    _sc("cold_ice_festival", "extreme_cold",
        "Outdoor Ice Sculpture Festival",
        {"time": {"season": "winter", "weather": "snowy"},
         "place": {"indoor_outdoor": "outdoor"},
         "occasion": {"activity": "casual_outing", "formality_required": "casual"}},
        gc_compat=["parka", "coat", "jacket", "sweater"],
        gc_incompat=["shorts", "tank_top", "t_shirt", "skirt"],
        q_explicit=["I'll be walking around an ice sculpture festival outdoors in freezing weather. Outfit?"],
        q_implicit=["Going to the ice festival this weekend. What should I wear?"],
        justification="Hours outdoors viewing ice sculptures in freezing weather rules out light clothing."),

    _sc("cold_new_year_countdown", "extreme_cold",
        "Outdoor New Year's Eve Countdown (Winter City)",
        {"time": {"season": "winter", "weather": "cold", "time_of_day": "night"},
         "place": {"indoor_outdoor": "outdoor"},
         "occasion": {"activity": "social_gathering", "formality_required": "casual"}},
        gc_compat=["parka", "coat", "jacket", "sweater"],
        gc_incompat=["shorts", "tank_top", "t_shirt"],
        q_explicit=["Going to an outdoor New Year countdown — it'll be freezing at midnight. Outfit?"],
        q_implicit=["Heading downtown for the New Year's Eve ball drop event. What should I wear?"],
        justification="Standing outdoors at midnight in winter cold requires heavy layering."),

    # ── ARCHETYPE 2: EXTREME HEAT (8) ─────────────────────
    _sc("heat_beach_day", "extreme_heat",
        "Scorching Beach Day",
        {"time": {"season": "summer", "weather": "hot_humid"},
         "place": {"venue": "beach", "indoor_outdoor": "outdoor"},
         "occasion": {"activity": "casual_outing", "formality_required": "very_casual"}},
        gc_compat=["shorts", "tank_top", "t_shirt"],
        gc_incompat=["parka", "coat", "trench_coat", "sweater", "blazer"],
        q_explicit=["It's 38°C and I'm heading to the beach for the whole day. What should I wear?"],
        q_implicit=["Planning a beach day this weekend in the peak of summer. Outfit?"],
        justification="Heavy outerwear at a scorching beach causes heatstroke risk."),

    _sc("heat_tropical_pool_party", "extreme_heat",
        "Tropical Resort Pool Party",
        {"time": {"season": "summer", "weather": "hot_humid"},
         "place": {"indoor_outdoor": "outdoor"},
         "occasion": {"activity": "social_gathering", "formality_required": "very_casual"}},
        gc_compat=["shorts", "tank_top", "t_shirt"],
        gc_incompat=["parka", "coat", "trench_coat", "sweater", "suit_jacket"],
        q_explicit=["Pool party at a tropical resort in sweltering heat. What should I wear?"],
        q_implicit=["Friends are throwing a poolside get-together at the resort. Outfit?"],
        justification="Parka or suit jacket at a tropical pool party is absurd."),

    _sc("heat_outdoor_festival", "extreme_heat",
        "Midsummer Outdoor Music Festival",
        {"time": {"season": "summer", "weather": "hot_humid"},
         "place": {"indoor_outdoor": "outdoor"},
         "occasion": {"activity": "social_gathering", "formality_required": "very_casual"}},
        gc_compat=["t_shirt", "tank_top", "shorts"],
        gc_incompat=["coat", "parka", "trench_coat", "sweater"],
        q_explicit=["Going to an all-day outdoor music festival in 35°C heat. Outfit advice?"],
        q_implicit=["Attending a summer music festival from noon to midnight. What should I wear?"],
        justification="All-day outdoor festival in extreme heat makes heavy outerwear a health hazard."),

    _sc("heat_desert_sightseeing", "extreme_heat",
        "Desert City Sightseeing (Peak Summer)",
        {"time": {"season": "summer", "weather": "hot_humid"},
         "place": {"indoor_outdoor": "outdoor"},
         "occasion": {"activity": "travel", "formality_required": "casual"}},
        gc_compat=["t_shirt", "shorts", "tank_top"],
        gc_incompat=["parka", "coat", "sweater", "trench_coat"],
        q_explicit=["Touring a desert city in 42°C heat. What should I wear?"],
        q_implicit=["Spending the day exploring Dubai in August. Outfit advice?"],
        justification="42°C desert heat in a parka/coat is a heatstroke emergency."),

    _sc("heat_summer_bbq", "extreme_heat",
        "Backyard Summer Barbecue",
        {"time": {"season": "summer", "weather": "sunny"},
         "place": {"indoor_outdoor": "outdoor"},
         "occasion": {"activity": "social_gathering", "formality_required": "very_casual"}},
        gc_compat=["t_shirt", "shorts", "tank_top"],
        gc_incompat=["parka", "coat", "sweater", "suit_jacket", "trench_coat"],
        q_explicit=["Friends invited me to a backyard BBQ on a hot summer afternoon. Outfit?"],
        q_implicit=["Heading to a cookout at a friend's place this sunny weekend. What should I wear?"],
        justification="Heavy winter outerwear at a casual summer BBQ is universally out of place."),

    _sc("heat_tropical_beach_wedding", "extreme_heat",
        "Tropical Beach Wedding (Guest)",
        {"time": {"season": "summer", "weather": "hot_humid"},
         "place": {"venue": "beach", "indoor_outdoor": "outdoor"},
         "occasion": {"activity": "ceremony_attendance", "formality_required": "smart_casual"}},
        gc_compat=["shirt", "blouse", "dress"],
        gc_incompat=["parka", "coat", "hoodie", "sweater"],
        q_explicit=["Attending a beach wedding in tropical heat. What should I wear?"],
        q_implicit=["Friend's getting married at a seaside venue in Bali. Outfit advice?"],
        justification="Parka to a tropical beach wedding is physically unbearable and socially absurd."),

    _sc("heat_water_park", "extreme_heat",
        "Water Park Visit (Peak Summer)",
        {"time": {"season": "summer", "weather": "hot_humid"},
         "place": {"indoor_outdoor": "outdoor"},
         "occasion": {"activity": "casual_outing", "formality_required": "very_casual"}},
        gc_compat=["t_shirt", "shorts", "tank_top"],
        gc_incompat=["coat", "parka", "sweater", "blazer", "trench_coat"],
        q_explicit=["Taking the family to a water park in scorching heat. What should I wear?"],
        q_implicit=["Spending the day at the water park this weekend. Outfit?"],
        justification="Coat/parka at a water park in summer heat is nonsensical."),

    _sc("heat_rooftop_party", "extreme_heat",
        "Rooftop Summer Party (Evening)",
        {"time": {"season": "summer", "weather": "hot_humid", "time_of_day": "evening"},
         "place": {"indoor_outdoor": "outdoor"},
         "occasion": {"activity": "social_gathering", "formality_required": "casual"}},
        gc_compat=["t_shirt", "shirt", "shorts", "blouse"],
        gc_incompat=["parka", "coat", "sweater", "trench_coat"],
        q_explicit=["Going to a rooftop party on a hot summer evening. What should I wear?"],
        q_implicit=["Friends are hosting a rooftop get-together downtown tonight. Outfit?"],
        justification="Summer rooftop party; heavy winter outerwear is uncomfortable."),

    # ── ARCHETYPE 3: ULTRA-FORMAL (10) ────────────────────
    _sc("formal_corporate_board", "ultra_formal",
        "Corporate Board Meeting",
        {"time": {"time_of_day": "daytime"},
         "place": {"venue": "office", "indoor_outdoor": "indoor"},
         "occasion": {"activity": "work_meeting", "formality_required": "formal"}},
        gc_compat=["suit_jacket", "blazer", "shirt", "blouse"],
        gc_incompat=["hoodie", "shorts", "tank_top", "t_shirt"],
        co_compat=["black", "navy", "gray", "white", "beige"],
        co_incompat=["orange", "yellow", "pink"],
        pa_compat=["solid", "striped"],
        pa_incompat=["graphic_print", "camouflage", "animal_print"],
        q_explicit=["I have a corporate board meeting today. The dress code is strictly formal. What should I wear?"],
        q_implicit=["Presenting to the executive board this afternoon. Outfit advice?"],
        justification="Hoodie/shorts at a corporate board meeting is universally inappropriate."),

    _sc("formal_national_award", "ultra_formal",
        "National Award Ceremony (Recipient)",
        {"time": {"time_of_day": "evening"},
         "place": {"indoor_outdoor": "indoor"},
         "occasion": {"activity": "ceremony_attendance", "formality_required": "formal"}},
        gc_compat=["suit_jacket", "blazer", "dress"],
        gc_incompat=["hoodie", "shorts", "tank_top", "t_shirt", "windbreaker"],
        co_compat=["black", "navy", "gray", "white"],
        co_incompat=["orange", "yellow"],
        pa_compat=["solid"],
        pa_incompat=["camouflage", "graphic_print", "animal_print"],
        q_explicit=["I'm receiving a national award tonight at a formal ceremony. What should I wear?"],
        q_implicit=["Attending an award ceremony at the national hall. Outfit?"],
        justification="Receiving a national award in a hoodie/shorts disrespects the institution."),

    _sc("formal_diplomatic_reception", "ultra_formal",
        "Diplomatic Reception",
        {"time": {"time_of_day": "evening"},
         "place": {"indoor_outdoor": "indoor"},
         "occasion": {"activity": "social_gathering", "formality_required": "formal"}},
        gc_compat=["suit_jacket", "blazer", "dress", "shirt", "blouse"],
        gc_incompat=["hoodie", "shorts", "tank_top", "t_shirt", "windbreaker"],
        co_compat=["black", "navy", "gray", "white", "beige"],
        co_incompat=["orange", "yellow", "pink"],
        pa_compat=["solid", "striped"],
        pa_incompat=["graphic_print", "camouflage", "animal_print"],
        q_explicit=["Attending a diplomatic reception tonight. Formal dress code. What should I wear?"],
        q_implicit=["Invited to an embassy reception. Outfit advice?"],
        justification="Diplomatic receptions have strict dress codes; casual wear is a protocol violation."),

    _sc("formal_opera_ballet", "ultra_formal",
        "Opera / Ballet Premiere (Dress Code)",
        {"time": {"time_of_day": "evening"},
         "place": {"venue": "concert_hall", "indoor_outdoor": "indoor"},
         "occasion": {"formality_required": "formal"}},
        gc_compat=["suit_jacket", "blazer", "dress", "shirt"],
        gc_incompat=["hoodie", "shorts", "tank_top", "t_shirt"],
        co_compat=["black", "navy", "gray", "white"],
        co_incompat=["orange", "yellow"],
        pa_compat=["solid"],
        pa_incompat=["camouflage", "graphic_print"],
        q_explicit=["Attending the opera premiere tonight — they enforce a dress code. What should I wear?"],
        q_implicit=["Going to opening night at the ballet. Outfit?"],
        justification="Opera/ballet premieres with dress codes prohibit casual attire."),

    _sc("formal_court_appearance", "ultra_formal",
        "Court Appearance",
        {"time": {"time_of_day": "daytime"},
         "place": {"indoor_outdoor": "indoor"},
         "occasion": {"formality_required": "formal"}},
        gc_compat=["suit_jacket", "blazer", "shirt", "blouse"],
        gc_incompat=["hoodie", "shorts", "tank_top", "t_shirt"],
        co_compat=["black", "navy", "gray", "white"],
        co_incompat=["orange", "yellow", "pink", "red"],
        pa_compat=["solid"],
        pa_incompat=["graphic_print", "camouflage", "animal_print"],
        q_explicit=["I have a court appearance tomorrow. What should I wear?"],
        q_implicit=["Need to appear before a judge next week. Outfit advice?"],
        justification="Court appearances require formal dress; casual wear may constitute contempt."),

    _sc("formal_fellowship_interview", "ultra_formal",
        "Scholarship / Fellowship Interview",
        {"time": {"time_of_day": "daytime"},
         "place": {"venue": "office", "indoor_outdoor": "indoor"},
         "occasion": {"activity": "work_meeting", "formality_required": "business_casual"}},
        gc_compat=["blazer", "shirt", "blouse", "suit_jacket"],
        gc_incompat=["hoodie", "shorts", "tank_top"],
        co_compat=["black", "navy", "gray", "white", "beige"],
        co_incompat=["orange", "yellow"],
        pa_compat=["solid", "striped"],
        pa_incompat=["graphic_print", "camouflage"],
        q_explicit=["I have a fellowship interview tomorrow at a university. What should I wear?"],
        q_implicit=["Interviewing for a research grant in person. Outfit?"],
        justification="Hoodie/shorts to a formal interview signals disrespect for the opportunity."),

    _sc("formal_fine_dining", "ultra_formal",
        "Fine Dining Restaurant (Dress Code)",
        {"time": {"time_of_day": "evening"},
         "place": {"venue": "restaurant", "indoor_outdoor": "indoor"},
         "occasion": {"formality_required": "formal"}},
        gc_compat=["blazer", "suit_jacket", "shirt", "dress", "blouse"],
        gc_incompat=["hoodie", "shorts", "tank_top", "t_shirt", "windbreaker"],
        pa_compat=["solid", "striped"],
        pa_incompat=["camouflage", "graphic_print"],
        q_explicit=["Dinner at a Michelin-starred restaurant with a strict dress code. What should I wear?"],
        q_implicit=["Reservation at the city's top fine-dining spot tonight. Outfit?"],
        justification="Fine dining with dress codes will refuse entry to guests in hoodies/shorts."),

    _sc("formal_graduation_ceremony", "ultra_formal",
        "University Graduation Ceremony (Guest)",
        {"place": {"indoor_outdoor": "indoor"},
         "occasion": {"activity": "ceremony_attendance", "formality_required": "business_casual"}},
        gc_compat=["blazer", "shirt", "blouse", "dress", "suit_jacket"],
        gc_incompat=["hoodie", "shorts", "tank_top"],
        pa_compat=["solid", "striped"],
        pa_incompat=["camouflage", "graphic_print"],
        q_explicit=["Attending my sister's graduation ceremony. What should I wear?"],
        q_implicit=["Going to a university commencement next week. Outfit?"],
        justification="Graduation ceremonies are formal occasions; casual wear disrespects graduates."),

    _sc("formal_investor_pitch", "ultra_formal",
        "Investor Pitch Presentation",
        {"time": {"time_of_day": "daytime"},
         "place": {"venue": "office", "indoor_outdoor": "indoor"},
         "occasion": {"activity": "work_meeting", "formality_required": "business_casual"}},
        gc_compat=["blazer", "shirt", "suit_jacket", "blouse"],
        gc_incompat=["hoodie", "shorts", "tank_top", "t_shirt"],
        co_compat=["black", "navy", "gray", "white"],
        co_incompat=["orange", "yellow"],
        pa_compat=["solid", "striped"],
        pa_incompat=["graphic_print", "camouflage", "animal_print"],
        q_explicit=["Pitching to venture capital investors today. Formal business attire expected. What should I wear?"],
        q_implicit=["Big investor meeting tomorrow morning. Outfit advice?"],
        justification="Investor pitches demand credibility; casual wear undermines professional trust."),

    _sc("formal_embassy_event", "ultra_formal",
        "Embassy Cultural Event",
        {"time": {"time_of_day": "evening"},
         "place": {"indoor_outdoor": "indoor"},
         "occasion": {"activity": "social_gathering", "formality_required": "formal"}},
        gc_compat=["blazer", "suit_jacket", "dress", "shirt", "blouse"],
        gc_incompat=["hoodie", "shorts", "tank_top", "t_shirt"],
        co_compat=["black", "navy", "gray", "white", "beige"],
        co_incompat=["orange", "yellow"],
        pa_compat=["solid"],
        pa_incompat=["camouflage", "graphic_print", "animal_print"],
        q_explicit=["Attending a cultural event at the embassy tonight. Formal dress required. Outfit?"],
        q_implicit=["Invited to an embassy cultural evening. What should I wear?"],
        justification="Embassy events follow diplomatic dress norms; casual attire is a protocol breach."),

    # ── ARCHETYPE 4: MOURNING / SOMBER (5) ────────────────
    _sc("mourn_funeral", "mourning_somber",
        "Funeral Service",
        {"place": {"indoor_outdoor": "mixed"},
         "occasion": {"activity": "ceremony_attendance", "formality_required": "formal"}},
        gc_compat=["suit_jacket", "blazer", "coat", "shirt", "blouse", "dress"],
        gc_incompat=["shorts", "tank_top", "hoodie", "t_shirt"],
        co_compat=["black", "navy", "gray"],
        co_incompat=["orange", "yellow", "pink", "red", "green"],
        pa_compat=["solid"],
        pa_incompat=["graphic_print", "camouflage", "animal_print", "floral", "polka_dot"],
        q_explicit=["I'm attending a funeral and need to dress appropriately. What should I wear?"],
        q_implicit=["Need an outfit for a memorial service this weekend. Advice?"],
        justification="Funerals universally demand dark, somber attire; bright/casual clothing is disrespectful."),

    _sc("mourn_memorial", "mourning_somber",
        "Memorial / Remembrance Service",
        {"place": {"indoor_outdoor": "mixed"},
         "occasion": {"activity": "ceremony_attendance", "formality_required": "formal"}},
        gc_compat=["suit_jacket", "blazer", "coat", "shirt", "dress"],
        gc_incompat=["shorts", "tank_top", "hoodie", "t_shirt"],
        co_compat=["black", "navy", "gray"],
        co_incompat=["orange", "yellow", "pink", "red"],
        pa_compat=["solid"],
        pa_incompat=["graphic_print", "camouflage", "animal_print", "floral"],
        q_explicit=["Attending a remembrance service for a colleague. What should I wear?"],
        q_implicit=["Going to a memorial ceremony next week. Outfit?"],
        justification="Memorial services share funeral solemnity; bright festive attire is disrespectful."),

    _sc("mourn_conservative_worship", "mourning_somber",
        "Conservative Religious Worship Service",
        {"place": {"indoor_outdoor": "indoor"},
         "occasion": {"formality_required": "business_casual"}},
        gc_compat=["shirt", "blouse", "blazer", "dress"],
        gc_incompat=["shorts", "tank_top", "t_shirt"],
        co_compat=["black", "navy", "gray", "white", "beige"],
        co_incompat=["orange", "yellow"],
        pa_compat=["solid", "striped"],
        pa_incompat=["graphic_print", "camouflage", "animal_print"],
        q_explicit=["Attending a conservative religious service. Modesty required. What should I wear?"],
        q_implicit=["Going to church/temple with a traditional congregation. Outfit advice?"],
        justification="Conservative religious services have modesty norms; tank tops/shorts widely prohibited."),

    _sc("mourn_vigil", "mourning_somber",
        "Candlelight Vigil",
        {"time": {"time_of_day": "night"},
         "place": {"indoor_outdoor": "outdoor"},
         "occasion": {"formality_required": "smart_casual"}},
        gc_compat=["coat", "jacket", "shirt", "sweater"],
        gc_incompat=["shorts", "tank_top"],
        co_compat=["black", "navy", "gray", "white"],
        co_incompat=["orange", "yellow", "pink", "red"],
        pa_compat=["solid"],
        pa_incompat=["graphic_print", "camouflage", "animal_print"],
        q_explicit=["Attending a candlelight vigil tonight. What should I wear?"],
        q_implicit=["Going to a community vigil. Outfit advice?"],
        justification="Candlelight vigils are solemn; bright festive colors are inappropriate."),

    _sc("mourn_condolence_visit", "mourning_somber",
        "Condolence Visit to Bereaved Family",
        {"place": {"indoor_outdoor": "indoor"},
         "occasion": {"formality_required": "smart_casual"}},
        gc_compat=["shirt", "blouse", "blazer", "sweater"],
        gc_incompat=["shorts", "tank_top", "hoodie"],
        co_compat=["black", "navy", "gray", "beige"],
        co_incompat=["orange", "yellow", "pink", "red"],
        pa_compat=["solid"],
        pa_incompat=["graphic_print", "animal_print", "floral"],
        q_explicit=["Visiting a bereaved family to offer condolences. What should I wear?"],
        q_implicit=["Paying respects to a friend's family. Outfit?"],
        justification="Visiting a grieving family in bright party colors is universally insensitive."),

    # ── ARCHETYPE 5: ATHLETIC (8) ─────────────────────────
    _sc("athletic_gym_weights", "athletic_physical",
        "Gym Weight Training",
        {"place": {"venue": "gym", "indoor_outdoor": "indoor"},
         "occasion": {"activity": "exercise", "formality_required": "very_casual"}},
        gc_compat=["t_shirt", "tank_top", "shorts"],
        gc_incompat=["suit_jacket", "blazer", "coat", "dress", "trench_coat"],
        q_explicit=["Heading to the gym for weight training. What should I wear?"],
        q_implicit=["Got a gym session after work today. Outfit?"],
        justification="Weight training in a suit/dress is physically restrictive and damages garments."),

    _sc("athletic_yoga", "athletic_physical",
        "Yoga / Pilates Class",
        {"place": {"venue": "gym", "indoor_outdoor": "indoor"},
         "occasion": {"activity": "exercise", "formality_required": "very_casual"}},
        gc_compat=["t_shirt", "tank_top"],
        gc_incompat=["coat", "blazer", "suit_jacket", "parka", "trench_coat", "dress"],
        q_explicit=["I have a yoga class tonight. What should I wear?"],
        q_implicit=["Starting Pilates this week. What's appropriate?"],
        justification="Yoga requires full-body flexibility; blazers/coats physically prevent poses."),

    _sc("athletic_marathon", "athletic_physical",
        "Marathon / Long-distance Running",
        {"place": {"indoor_outdoor": "outdoor"},
         "occasion": {"activity": "exercise", "formality_required": "very_casual"}},
        gc_compat=["t_shirt", "tank_top", "shorts"],
        gc_incompat=["coat", "blazer", "suit_jacket", "dress", "parka", "trench_coat"],
        q_explicit=["Running a half-marathon this weekend. What should I wear?"],
        q_implicit=["Training for my first marathon — what's the right outfit?"],
        justification="Running 42km in a coat/blazer is physically impossible and dangerous."),

    _sc("athletic_indoor_sports", "athletic_physical",
        "Indoor Team Sports (Basketball / Futsal)",
        {"place": {"venue": "gym", "indoor_outdoor": "indoor"},
         "occasion": {"activity": "exercise", "formality_required": "very_casual"}},
        gc_compat=["t_shirt", "shorts", "tank_top"],
        gc_incompat=["blazer", "suit_jacket", "coat", "dress", "trench_coat"],
        q_explicit=["Playing indoor basketball tonight. What should I wear?"],
        q_implicit=["Joining a futsal league — what's the right outfit for practice?"],
        justification="Team sports in a blazer/dress restricts movement and risks injury."),

    _sc("athletic_rock_climbing", "athletic_physical",
        "Indoor Rock Climbing",
        {"place": {"indoor_outdoor": "indoor"},
         "occasion": {"activity": "exercise", "formality_required": "very_casual"}},
        gc_compat=["t_shirt", "shorts", "tank_top"],
        gc_incompat=["coat", "blazer", "suit_jacket", "dress", "parka"],
        q_explicit=["Going indoor rock climbing. What should I wear?"],
        q_implicit=["Friend invited me to the climbing gym. Outfit advice?"],
        justification="Rock climbing in a coat/dress is a safety hazard."),

    _sc("athletic_swimming", "athletic_physical",
        "Swimming Pool Lap Session",
        {"place": {"indoor_outdoor": "indoor"},
         "occasion": {"activity": "exercise", "formality_required": "very_casual"}},
        gc_compat=["t_shirt", "shorts", "tank_top"],
        gc_incompat=["coat", "blazer", "suit_jacket", "parka", "sweater", "trench_coat"],
        q_explicit=["Heading to the pool for lap swimming. What should I wear?"],
        q_implicit=["Starting regular swimming sessions. What to bring?"],
        justification="Wearing a parka/blazer to swim laps is absurd."),

    _sc("athletic_tennis", "athletic_physical",
        "Tennis Match",
        {"place": {"indoor_outdoor": "outdoor"},
         "occasion": {"activity": "exercise", "formality_required": "very_casual"}},
        gc_compat=["t_shirt", "shorts", "tank_top"],
        gc_incompat=["coat", "blazer", "suit_jacket", "parka", "dress", "trench_coat"],
        q_explicit=["Tennis match this afternoon. What should I wear?"],
        q_implicit=["Joined a weekend tennis club — what to wear on court?"],
        justification="Playing tennis in a coat/parka is physically impossible."),

    _sc("athletic_dance_class", "athletic_physical",
        "Dance Class (Contemporary / Hip-hop)",
        {"place": {"indoor_outdoor": "indoor"},
         "occasion": {"activity": "exercise", "formality_required": "very_casual"}},
        gc_compat=["t_shirt", "tank_top", "shorts"],
        gc_incompat=["coat", "blazer", "suit_jacket", "parka", "trench_coat"],
        q_explicit=["Taking a hip-hop dance class tonight. What should I wear?"],
        q_implicit=["Signed up for contemporary dance lessons. Outfit advice?"],
        justification="Dance class requires full-body mobility; outerwear prevents movement."),

    # ── ARCHETYPE 6: WEATHER EXTREME (5) ──────────────────
    _sc("weather_typhoon", "weather_extreme",
        "Typhoon / Hurricane Errands",
        {"time": {"weather": "rainy"},
         "place": {"indoor_outdoor": "outdoor"},
         "occasion": {"activity": "errands"}},
        gc_compat=["windbreaker", "coat", "parka", "jacket"],
        gc_incompat=["dress", "tank_top", "shorts", "skirt"],
        q_explicit=["A typhoon is hitting and I have to go out for errands. What should I wear?"],
        q_implicit=["Need to run essential errands during the storm. Outfit?"],
        justification="Typhoon-force wind and rain makes exposed-skin clothing dangerous."),

    _sc("weather_monsoon", "weather_extreme",
        "Monsoon Season All-Day Outdoor Work",
        {"time": {"season": "summer", "weather": "rainy"},
         "place": {"indoor_outdoor": "outdoor"},
         "occasion": {"activity": "errands"}},
        gc_compat=["windbreaker", "jacket"],
        gc_incompat=["dress", "tank_top", "blazer", "suit_jacket"],
        q_explicit=["Working outside all day during monsoon rains. What should I wear?"],
        q_implicit=["Field work during the rainy season. What's the right outfit?"],
        justification="Working outdoors in monsoon downpour in a dress/blazer is impractical."),

    _sc("weather_hailstorm", "weather_extreme",
        "Hailstorm Emergency Evacuation",
        {"time": {"weather": "cold"},
         "place": {"indoor_outdoor": "outdoor"},
         "occasion": {"activity": "errands"}},
        gc_compat=["coat", "jacket", "parka", "windbreaker"],
        gc_incompat=["tank_top", "shorts", "t_shirt", "dress"],
        q_explicit=["Hailstorm warning — need to walk home. What should I wear?"],
        q_implicit=["Caught outside during a sudden hailstorm. What to wear next time?"],
        justification="Hailstones on bare skin cause injury; protective outerwear essential."),

    _sc("weather_freezing_rain", "weather_extreme",
        "Freezing Rain / Ice Storm Commute",
        {"time": {"season": "winter", "weather": "rainy"},
         "place": {"indoor_outdoor": "outdoor"},
         "occasion": {"activity": "travel"}},
        gc_compat=["coat", "parka", "jacket", "windbreaker"],
        gc_incompat=["shorts", "tank_top", "t_shirt", "dress"],
        q_explicit=["Freezing rain and icy roads — walking to work. What should I wear?"],
        q_implicit=["Ice storm making my commute treacherous. Outfit?"],
        justification="Freezing rain + sub-zero wind chill makes light clothing hypothermia-inducing."),

    _sc("weather_dust_storm", "weather_extreme",
        "Sandstorm / Dust Storm Outdoor",
        {"time": {"weather": "windy"},
         "place": {"indoor_outdoor": "outdoor"},
         "occasion": {"activity": "errands"}},
        gc_compat=["windbreaker", "jacket", "coat"],
        gc_incompat=["tank_top", "shorts", "dress", "skirt"],
        q_explicit=["Dust storm rolling in and I need to cross town. What should I wear?"],
        q_implicit=["Living in a desert city — sandstorm season. What to wear outdoors?"],
        justification="Sand/dust exposure on bare skin causes abrasion; full coverage needed."),

    # ── ARCHETYPE 7: SEMI-FORMAL SOCIAL (10) ──────────────
    _sc("social_alumni_dinner", "semi_formal_social",
        "University Alumni Formal Dinner",
        {"time": {"time_of_day": "evening"},
         "place": {"venue": "restaurant", "indoor_outdoor": "indoor"},
         "occasion": {"activity": "social_gathering", "formality_required": "business_casual"}},
        gc_compat=["blazer", "shirt", "blouse", "dress"],
        gc_incompat=["hoodie", "shorts", "tank_top"],
        pa_compat=["solid", "striped"],
        pa_incompat=["camouflage", "graphic_print"],
        q_explicit=["Alumni formal dinner tonight at a hotel ballroom. What should I wear?"],
        q_implicit=["Going to my university alumni reunion dinner. Outfit?"],
        justification="Alumni formal dinners have dress codes; hoodies/shorts would be turned away."),

    _sc("social_gallery_opening", "semi_formal_social",
        "Art Gallery Opening / Vernissage",
        {"time": {"time_of_day": "evening"},
         "place": {"venue": "art_gallery", "indoor_outdoor": "indoor"},
         "occasion": {"activity": "social_gathering", "formality_required": "smart_casual"}},
        gc_compat=["blazer", "shirt", "blouse", "dress"],
        gc_incompat=["shorts", "tank_top", "hoodie"],
        q_explicit=["Attending an art gallery opening tonight. What should I wear?"],
        q_implicit=["Got invited to a vernissage at a downtown gallery. Outfit?"],
        justification="Gallery openings are smart-casual events; shorts/hoodie signal disinterest."),

    _sc("social_company_gala", "semi_formal_social",
        "Company Annual Gala / Holiday Party",
        {"time": {"time_of_day": "evening"},
         "place": {"indoor_outdoor": "indoor"},
         "occasion": {"activity": "social_gathering", "formality_required": "business_casual"}},
        gc_compat=["blazer", "shirt", "blouse", "dress", "suit_jacket"],
        gc_incompat=["hoodie", "shorts", "tank_top", "t_shirt"],
        pa_compat=["solid", "striped"],
        pa_incompat=["camouflage", "graphic_print"],
        q_explicit=["Company annual gala tonight. Smart-casual expected. What should I wear?"],
        q_implicit=["Going to the office holiday party. Outfit advice?"],
        justification="Company galas have implicit dress codes; casual wear harms professional reputation."),

    _sc("social_first_date_upscale", "semi_formal_social",
        "First Date at Upscale Restaurant",
        {"time": {"time_of_day": "evening"},
         "place": {"venue": "restaurant", "indoor_outdoor": "indoor"},
         "occasion": {"activity": "first_date", "formality_required": "smart_casual"}},
        gc_compat=["shirt", "blouse", "blazer", "dress"],
        gc_incompat=["hoodie", "shorts", "tank_top"],
        pa_compat=["solid", "striped", "floral"],
        pa_incompat=["camouflage", "graphic_print"],
        q_explicit=["First date at an upscale restaurant tonight. What should I wear?"],
        q_implicit=["Dinner date at a nice restaurant. Outfit advice?"],
        justification="Showing up to an upscale restaurant date in a hoodie/shorts signals disrespect."),

    _sc("social_business_dinner", "semi_formal_social",
        "Business Dinner with Client",
        {"time": {"time_of_day": "evening"},
         "place": {"venue": "restaurant", "indoor_outdoor": "indoor"},
         "occasion": {"activity": "work_meeting", "formality_required": "business_casual"}},
        gc_compat=["blazer", "shirt", "suit_jacket", "blouse"],
        gc_incompat=["hoodie", "shorts", "tank_top", "t_shirt"],
        co_compat=["black", "navy", "gray", "white", "beige"],
        co_incompat=["orange", "yellow"],
        pa_compat=["solid", "striped"],
        pa_incompat=["graphic_print", "camouflage", "animal_print"],
        q_explicit=["Business dinner with an important client. Professional attire expected. What should I wear?"],
        q_implicit=["Taking a client out for dinner. Outfit?"],
        justification="Business dinners represent the company; casual wear is a professional failure."),

    _sc("social_wedding_reception", "semi_formal_social",
        "Indoor Wedding Reception (Guest)",
        {"place": {"venue": "wedding_venue", "indoor_outdoor": "indoor"},
         "occasion": {"activity": "ceremony_attendance", "formality_required": "smart_casual"}},
        gc_compat=["blazer", "suit_jacket", "dress", "shirt", "blouse"],
        gc_incompat=["hoodie", "shorts", "tank_top", "t_shirt"],
        co_compat=["navy", "beige", "blue", "gray", "green", "purple"],
        co_incompat=["orange", "yellow"],
        pa_compat=["solid", "striped", "floral"],
        pa_incompat=["camouflage", "graphic_print", "animal_print"],
        q_explicit=["Attending a wedding reception at a hotel ballroom. What should I wear?"],
        q_implicit=["Friend's wedding reception next Saturday. Outfit?"],
        justification="Wearing shorts/hoodie to a wedding reception insults the couple."),

    _sc("social_charity_auction", "semi_formal_social",
        "Charity Auction Gala",
        {"time": {"time_of_day": "evening"},
         "place": {"indoor_outdoor": "indoor"},
         "occasion": {"activity": "social_gathering", "formality_required": "formal"}},
        gc_compat=["suit_jacket", "blazer", "dress"],
        gc_incompat=["hoodie", "shorts", "tank_top", "t_shirt"],
        co_compat=["black", "navy", "gray", "white"],
        co_incompat=["orange", "yellow"],
        pa_compat=["solid"],
        pa_incompat=["camouflage", "graphic_print", "animal_print"],
        q_explicit=["Attending a charity auction gala tonight. Black-tie. What should I wear?"],
        q_implicit=["Invited to a charity fundraiser. Outfit advice?"],
        justification="Charity galas are formal fundraising events; casual wear is out of place."),

    _sc("social_theater_premiere", "semi_formal_social",
        "Theater Premiere Night",
        {"time": {"time_of_day": "evening"},
         "place": {"venue": "concert_hall", "indoor_outdoor": "indoor"},
         "occasion": {"formality_required": "business_casual"}},
        gc_compat=["blazer", "shirt", "dress", "blouse"],
        gc_incompat=["hoodie", "shorts", "tank_top", "t_shirt"],
        pa_compat=["solid", "striped"],
        pa_incompat=["camouflage", "graphic_print"],
        q_explicit=["Theater premiere tonight — smart-casual minimum. What should I wear?"],
        q_implicit=["Going to opening night at the theater. Outfit?"],
        justification="Theater premieres expect smart-casual minimum; hoodies/shorts are inappropriate."),

    _sc("social_wine_tasting", "semi_formal_social",
        "Wine Tasting Event at Vineyard",
        {"place": {"indoor_outdoor": "mixed"},
         "occasion": {"activity": "social_gathering", "formality_required": "smart_casual"}},
        gc_compat=["shirt", "blouse", "blazer", "dress"],
        gc_incompat=["hoodie", "tank_top", "shorts"],
        q_explicit=["Attending a wine tasting at a vineyard. What should I wear?"],
        q_implicit=["Invited to a vineyard tour and tasting. Outfit advice?"],
        justification="Wine tasting events are semi-formal social occasions; hoodies/shorts are out of place."),

    _sc("social_book_launch", "semi_formal_social",
        "Book Launch Party",
        {"time": {"time_of_day": "evening"},
         "place": {"indoor_outdoor": "indoor"},
         "occasion": {"activity": "social_gathering", "formality_required": "smart_casual"}},
        gc_compat=["shirt", "blouse", "blazer", "dress"],
        gc_incompat=["hoodie", "tank_top", "shorts"],
        q_explicit=["Going to a friend's book launch party. What should I wear?"],
        q_implicit=["Invited to a literary event at a bookstore bar. Outfit?"],
        justification="Book launch parties are smart-casual cultural events."),

    # ── ARCHETYPE 8: CASUAL OUTDOOR (6) ───────────────────
    _sc("casual_park_picnic", "casual_outdoor",
        "Weekend Park Picnic",
        {"time": {"season": "spring", "weather": "sunny"},
         "place": {"venue": "park", "indoor_outdoor": "outdoor"},
         "occasion": {"activity": "casual_outing", "formality_required": "very_casual"}},
        gc_compat=["t_shirt", "shorts", "dress", "hoodie", "jeans"],
        gc_incompat=["suit_jacket", "blazer", "trench_coat"],
        q_explicit=["Picnic at the park on a sunny afternoon. What should I wear?"],
        q_implicit=["Meeting friends at the park for a lazy Sunday. Outfit?"],
        justification="Suit jacket to a park picnic is universally over-dressed."),

    _sc("casual_amusement_park", "casual_outdoor",
        "Amusement Park All-Day Visit",
        {"place": {"indoor_outdoor": "outdoor"},
         "occasion": {"activity": "casual_outing", "formality_required": "very_casual"}},
        gc_compat=["t_shirt", "shorts", "hoodie", "jeans"],
        gc_incompat=["suit_jacket", "blazer", "trench_coat", "coat", "dress"],
        q_explicit=["Spending the whole day at an amusement park. What should I wear?"],
        q_implicit=["Taking the family to the theme park. Outfit advice?"],
        justification="Formal wear at amusement parks restricts rides and movement."),

    _sc("casual_flea_market", "casual_outdoor",
        "Weekend Flea Market Browse",
        {"place": {"indoor_outdoor": "outdoor"},
         "occasion": {"activity": "casual_outing", "formality_required": "very_casual"}},
        gc_compat=["t_shirt", "hoodie", "jeans", "shorts"],
        gc_incompat=["suit_jacket", "blazer", "trench_coat"],
        q_explicit=["Browsing a flea market this weekend. What should I wear?"],
        q_implicit=["Heading to the weekend market for vintage finds. Outfit?"],
        justification="A suit at a flea market is universally overdressed."),

    _sc("casual_camping_spring", "casual_outdoor",
        "Spring / Autumn Camping Trip",
        {"time": {"season": "spring"},
         "place": {"indoor_outdoor": "outdoor"},
         "occasion": {"activity": "travel", "formality_required": "very_casual"}},
        gc_compat=["hoodie", "jacket", "jeans", "t_shirt"],
        gc_incompat=["suit_jacket", "blazer", "dress", "trench_coat"],
        q_explicit=["Going camping for the weekend in mild spring weather. What should I wear?"],
        q_implicit=["Planning an outdoor camping trip with friends. Outfit?"],
        justification="Camping in a blazer/suit is impractical and damages the garment."),

    _sc("casual_dog_park", "casual_outdoor",
        "Dog Park Morning Walk",
        {"time": {"time_of_day": "morning"},
         "place": {"venue": "park", "indoor_outdoor": "outdoor"},
         "occasion": {"activity": "casual_outing", "formality_required": "very_casual"}},
        gc_compat=["t_shirt", "hoodie", "jeans", "shorts"],
        gc_incompat=["suit_jacket", "blazer", "trench_coat", "dress"],
        q_explicit=["Taking my dog to the park for a morning walk. What should I wear?"],
        q_implicit=["Daily dog walk routine — what's a good outfit?"],
        justification="Walking a dog in a suit/formal dress is universally impractical."),

    _sc("casual_street_food_festival", "casual_outdoor",
        "Street Food Festival",
        {"place": {"venue": "city_street", "indoor_outdoor": "outdoor"},
         "occasion": {"activity": "casual_outing", "formality_required": "very_casual"}},
        gc_compat=["t_shirt", "hoodie", "jeans", "shorts"],
        gc_incompat=["suit_jacket", "blazer", "trench_coat"],
        q_explicit=["Going to a street food festival this weekend. What should I wear?"],
        q_implicit=["Food truck rally downtown tonight. Outfit?"],
        justification="Eating street food in a suit is overdressed and stain-prone."),
]


# ═══════════════════════════════════════════════════════════
#  HELPERS
# ═══════════════════════════════════════════════════════════

def get_constrained_axes(scenario):
    """Which axes does this scenario constrain?"""
    axes = []
    for ax in ("garment_category", "color", "pattern"):
        c = scenario.get(ax)
        if c is not None and c.get("incompatible"):
            axes.append(ax)
    return axes


def get_scenario_by_id(sid):
    for sc in CANONICAL_SCENARIOS:
        if sc["scenario_id"] == sid:
            return sc
    return None


def scenarios_by_archetype():
    out = {}
    for sc in CANONICAL_SCENARIOS:
        out.setdefault(sc["archetype"], []).append(sc)
    return out


def count_axis_slots():
    total = 0
    by_axis = {"garment_category": 0, "color": 0, "pattern": 0}
    for sc in CANONICAL_SCENARIOS:
        for ax in get_constrained_axes(sc):
            by_axis[ax] += 1
            total += 1
    return total, by_axis


if __name__ == "__main__":
    total, by_axis = count_axis_slots()
    print(f"Scenarios: {len(CANONICAL_SCENARIOS)}")
    print(f"Axis slots/user: {total}")
    for ax, n in by_axis.items():
        print(f"  {ax}: {n}")
